test:
  allow_failure: true
  artifacts:
    expire_in: 30 days
    paths:
      - target/site/serenity
      - public
    when: always
  script:
    - mkdir .public
    - "mvn clean compile verify"
    - cp -r * .public
    - mv .public public
    paths:
      - public
  only:
    - master
  tags:
    - ci
    - shell
