---
pages:
  artifacts:
    paths:
      - public
  only:
    - master
  script:
    - "mkdir .public"
    - "cp -r * .public"
    - "mv .public public"
test:
  allow_failure: true
  artifacts:
    expire_in: "30 days"
    paths:
      - target/site/serenity
      - public
    when: always
  only:
    - master
  script:
    - "mvn clean compile verify"
  tags:
    - ci
    - shell
