test:
  allow_failure: true
  artifacts:
    expire_in: ~
    paths:
      - target/site/serenity
      - public
    when: always
  script:
    - "mvn clean compile verify"
  tags:
    - ci
    - shell